## S14a: Lab 2 - Numpy

Below is quick quickstart with numpy, designed to give new users a sense of how the library works. There is so much more functionality, and developers have provided an incredible [tutorial](https://numpy.org/devdocs/user/quickstart.html) for anyone ready for a deeper dive.

Also for need X need guidance, take a look at the [reference](https://numpy.org/doc/1.18/reference/index.html).

### The basics: 1D and 2D arrays

In [1]:
# Import numpy

import numpy as np

In [2]:
# Build a one dimensional (1D) numpy array directly

numpy_1d = np.array([1, 2, 3])
numpy_1d

array([1, 2, 3])

In [3]:
# Take a look at 1D dimensionality

np.ndim(numpy_1d)

1

In [4]:
# Take a look at 1D shape - (length, 

np.shape(numpy_1d)

(3,)

In [5]:
# Grab values at certain positions in 1D

numpy_1d[0]

1

In [6]:
# Build a two dimensional (2D) numpy array - "array of arrays"

numpy_2d = np.array([[4, 5, 6], [7, 8, 9]])
numpy_2d

array([[4, 5, 6],
       [7, 8, 9]])

In [7]:
# Take a look at 2D dimensionality

np.ndim(numpy_2d)

2

In [8]:
# Take a look at a 2D shape - (#row, #col)

np.shape(numpy_2d)

(2, 3)

In [17]:
# !!!YOUR TURN!!!

# Grab values at certain positions in 2D

numpy_2d[0, 1]

5

In [18]:
# Slice out portions of the array

numpy_2d[1, 1:3]

array([8, 9])

In [19]:
# Grab with condition
numpy_2d[numpy_2d >= 6]

array([6, 7, 8, 9])

In [20]:
# Reshape your 3d array, reversing rows and cols

numpy_2d.reshape(3, 2)

array([[4, 5],
       [6, 7],
       [8, 9]])

### Building / transforming arrays - selections

In [21]:
# Build a numpy array using a range - (start at, up to, step size)

np.arange(3, 10, 3)

array([3, 6, 9])

In [22]:
# Build a numpy array using evenly spaced points in a range - (start at, up to, breakpoints)

np.linspace(3, 15, 5)

array([ 3.,  6.,  9., 12., 15.])

In [23]:
# Create 1D array of 0s

np.zeros(3)

array([0., 0., 0.])

In [24]:
# Create 2D arrayy of 1s

np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
# !!!YOUR TURN!!!
# https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html
# Create 2D array of random numbers
randC = np.random.random_sample((2,3))
randC

array([[0.2791912 , 0.61126205, 0.39330136],
       [0.46823816, 0.49219645, 0.74255752]])

In [37]:
# Get min and max
[randC.min(), randC.max()]

[0.2791911976885765, 0.742557518973713]

### Math, [ref.](https://numpy.org/doc/1.18/reference/routines.math.html)

In [39]:
# Addition / subtraction (you can define type)

npx = np.array([[1, 2], [3, 4]], dtype=np.float64)
npy = np.array([[5, 6], [7, 8]], dtype=np.float64)

print('+.', np.add(npx, npy))
print('-.', np.subtract(npx, npy))

+. [[ 6.  8.]
 [10. 12.]]
-. [[-4. -4.]
 [-4. -4.]]


In [40]:
# Multiplication / divide

print('*.', np.multiply(npx, npy))
print('/.', np.divide(npx, npy))


*. [[ 5. 12.]
 [21. 32.]]
/. [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [41]:
# And other nice Math functions

print(np.sqrt(npx))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [51]:
# !!!YOUR TURN!!!

# Path attention to the second argument - the axis
print(np.sum(npx, axis=0))
print(np.sum(npx, axis=1))

[4. 6.]
[3. 7.]


In [ ]:
# Broadcasting - when performing mathematical operations, shape matters

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

for i in range(len(x)):
    y[i, :] = x[i, :] + v

print(y)

In [ ]:
# Copying - if you need your changes not to effect the original array, make a copy
y_copy = y.copy()
y_copy[0][0:] = -9999
print(y)
print(y_copy)